name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        env:
          BASE_PATH: "/cubesheet"
        run: |
          npm run build
          touch build/.nojekyll
      - name: Verify Build Output
        run: ls -la build/
      - name: Check Build Output Exists
        run: |
          if [ ! -d "build" ] || [ -z "$(ls -A build)" ]; then
            echo "Error: Build directory is missing or empty!"
            exit 1
          fi
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build/"
          include-hidden-files: true

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
