name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4 (latest as of 2025)
      - uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        env:
          BASE_PATH: "/cubesheet"
        run: |
          npm run build
          mkdir -p build && touch build/.nojekyll
      - name: Verify Build Output
        run: ls -la build/
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3 # Updated to v3 (latest as of 2025)
        with:
          path: "build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2 # Updated to v2 (check compatibility)
